### ISSUE TITLE
"benchmark/benchmark.h" missing

### ISSUE THREAD

**Issue by dvtate** [CoffeeBeforeArch/gaussian_elimination#1]
I came here from [your video](https://www.youtube.com/watch?v=6WN-fHN5O7s), but the code here seems different (looks easier to read at least). But it seems you forgot to include a header in the github repo, so the code here won't compile. Would recommend adding a `Makefile`.

```
[tate@archbook src]$ LANG=en g++ *.cpp -Wall -Wextra -g -lpthread -lbenchmark
benchmark.cpp:3:10: fatal error: benchmark/benchmark.h: No such file or directory
    3 | #include "benchmark/benchmark.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by dvtate** [comment]
I realize now that you included a `Makefile` but it produces the same error.
```
[tate@archbook src]$ LANG=en make
g++ -c serial_ge.cpp -O3 -march=native -mtune=native -flto -fuse-linker-plugin --std=c++2a
g++ -c parallel_ge.cpp -O3 -march=native -mtune=native -flto -fuse-linker-plugin --std=c++2a
g++ benchmark.cpp serial_ge.o parallel_ge.o -O3 -march=native -mtune=native -flto -fuse-linker-plugin --std=c++2a -lbenchmark -lpthread -o ge_bench
benchmark.cpp:3:10: fatal error: benchmark/benchmark.h: No such file or directory
    3 | #include "benchmark/benchmark.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7: benchmark] Error 1
[tate@archbook src]$ 
```

**Comment by CoffeeBeforeArch** [comment]
`benchmark/benchmark.h` is a header from the Google microbenchmark library. You likely don't have it installed on your machine. 

This is also not the code from that video (this is a dedicated repo for Gaussian Elimination code that I was planning on writing a few serial+parallel implementations). The original code is in this repo - https://github.com/CoffeeBeforeArch/practical_parallelism_in_cpp (note, I haven't updated that repo since Dec. 2019, so I'm not sure what state I left that code in).
